import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import navBar from '../components/navBar'
import Inputs from '../components/Inputs'
/**Welcome to <a href="https://nextjs.org">Next.js!</a>*/

export default function Home() {
  return (
    <div className={styles.container}>
    <Head>
      <title>APOS</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/APOS1.png" />
    </Head>
   
<div class="padding-20vh">
  <Link href="/loginAuth">
<button>
  <Image src="/back.png" width={25} height={21} />
</button>
</Link>  
</div>

  <div>
      <navBar/>
  </div>
 

  </div>
  )
}

/* Y ESTA MIERDA QUE NO ANDA PORQUE SOY TAN PELOTUDO QUE NO PUEDO 
HACER UN NAVBAR DE MIERDA*/