import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
/**Welcome to <a href="https://nextjs.org">Next.js!</a>*/

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>APOS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/APOS1.png" />
      </Head>

      <main className={styles.main}>
      <Link href="/loginAuth">
      <button>
        <Image src="/APOS2.png" alt="Vercel Logo" width={295} height={308} />
      </button>
      </Link>  
          
        <h1 className={styles.title}>
         Estamos para cuidarte
        </h1>
      </main>

     
    </div>
  )
}
