import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Inputs from '../components/Inputs'

export default function Home() {
    return (
      <div className={styles.container}>
      
        <Head>
          <title>APOS</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/APOS1.png" />
        </Head>
<div class="padding-20vh">

      <Link href="/loginAuth">
      <button>
        <Image src="/back.png" width={25} height={21} />
    </button>
      </Link>
        
          <h1 className={styles.title1} >
           Ingresá con tu cuenta
          </h1>
</div>

        <div>
            <Inputs/>
        </div>
       
    

      </div>
    )
  }
  