import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
    return (
      <div className={styles.container}>
        <Head>
          <title>APOS</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/APOS1.png" />
        </Head>
  
        <main className={styles.mainw}>

        <Image src="/APOS1.png" alt="APOS Logo" width={215} height={225} />
        <h1 className={styles.title1} >
           Ingresá con tu cuenta
          </h1>

 
          <Link href="/login">
        <div>
        <button className={styles.buttom}>Ingresar con Facebook</button>
        </div>
        </Link>  
        <Link href="/login">
        <div>
        <button className={styles.buttom1}>Ingresar con Gmail</button>
        </div>
        </Link>  
        <Link href="/login">
        <div>
        <button className={styles.buttom2}>
        <h1 className={styles.text2}>Ingresar con N° de Afiliado</h1>
        </button>
        </div>
        </Link>  
            
          
        </main>
  
      </div>
    )
  }
  